# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 05:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id_blog', models.AutoField(primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=140)),
                ('title', models.CharField(max_length=140)),
            ],
        ),
    ]
