# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id_blog',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
